server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/searchBook
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
kakao:
  host: https://dapi.kakao.com
  apikey: a49ddde24cf0941a7e94253849946401
  bookpath: /v3/search/book
