CREATE TABLE TBL_USER(id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL);
INSERT INTO TBL_USER values(1, 'admin', '{noop}admin');

CREATE TABLE TBL_HIST(id INT AUTO_INCREMENT PRIMARY KEY, userId INT NOT NULL, keyword VARCHAR(255) NOT NULL, inputdate DATETIME NOT NULL);